name: lan_chat
description: Secure LAN Communication Platform Client.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.1

  # Networking
  http: ^1.2.0
  dio: ^5.4.0
  web_socket_channel: ^2.4.0

  # Storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0

  # Utils
  uuid: ^4.3.3
  intl: ^0.19.0
  json_annotation: ^4.8.1
  file_picker: ^8.0.7
  path: ^1.9.1
  path_provider: ^2.1.5
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
